{{- if and .Values.global.setupScope .Values.global.setupApps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terra-scope
  namespace: terra-cargo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:serenditree/stem.git'
    path: plots/terra/charts/scope
    targetRevision: dev
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: terra-scope
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
