{{- with .Values.kafka }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: {{ .name }}
spec:
  replicas: {{ .replicas }}
  roles:
    - controller
    - broker
  storage:
    {{- if hasSuffix "local" $.Values.global.context }}
    type: ephemeral
    {{- else }}
    type: persistent-claim
    size: {{ .storage }}Gi
    deleteClaim: false
    kraftMetadata: shared
    {{- end }}
{{- end }}
