########################################################################################################################
# Global
########################################################################################################################
global:
  context: ~
  clusterDomain: ~
  host: ~
  issuer: ~
  stage: ~
  zone: ~
  revision: "dev"
  cdNamespace: "terra-argocd"
  destinationServer: "https://kubernetes.default.svc"
  repository: "git@github.com:serenditree/stem.git"
  terraPath: "charts/terra"
  terraPrefix: "terra-"
  rootPath: "charts/root"
  rootPrefix: "root-"
  path: "charts"
########################################################################################################################
# Serenditree
########################################################################################################################
serenditree:
  wave: 0
  name: serenditree
########################################################################################################################
# Terra
########################################################################################################################
terraArgocd:
  wave: 1
  name: terra-argocd
  namespace: terra-argocd
terraCerts:
  enabled: true
  wave: 2
  name: terra-certs
  namespace: terra-certs
  parameters:
    email: ~
terraStreams:
  enabled: true
  wave: 3
  name: terra-streams
  namespace: terra-streams
  parameters:
    kafdrop:
      enabled: false
terraScope:
  enabled: true
  wave: 4
  name: terra-scope
  namespace: terra-scope
terraTraces:
  enabled: true
  wave: 5
  name: terra-traces
  namespace: terra-traces
  parameters:
    config:
      storage:
        s3:
          access_key_id: ~
          secret_access_key: ~
      metastore_uri: ~
      default_index_root_uri: ~
terraCilium:
  wave: 6
  name: terra-cilium
  namespace: kube-system
  parameters:
    cluster:
      name: ~
    k8sServiceHost: ~
terraCollect:
  enabled: true
  wave: 7
  name: terra-collect
  namespace: terra-collect
terraCache:
  wave: 8
  name: terra-cache
  namespace: terra-ingress
terraIngress:
  enabled: true
  wave: 9
  name: terra-ingress
  namespace: terra-ingress
terraScale:
  enabled: false
  wave: 100
  name: terra-scale
  namespace: kube-system
  parameters:
    minSize: 3
    maxSize: 5
    apikey: ~
    secret: ~
    autoscalingGroups: []
terraTekton:
  enabled: true
  wave: 10
  name: terra-tekton
  namespace: terra-tekton
  parameters:
    webhook: ~
    basic:
      github: ~
      quay: ~
      redhat: ~
########################################################################################################################
# Root
########################################################################################################################
rootMap:
  enabled: true
  wave: 11
  name: root-map
  namespace: serenditree
  parameters:
    data:
      apikey: ~
      secret: ~
rootSeed:
  enabled: true
  wave: 12
  name: root-seed
  namespace: serenditree
  parameters:
    auth:
      usernames: ~
      passwords: ~
      rootPassword: ~
rootUser:
  enabled: true
  wave: 13
  name: root-user
  namespace: serenditree
  parameters:
    db:
      user: ~
      password: ~
    rootUser:
      password: ~
rootWind:
  enabled: true
  wave: 14
  name: root-wind
  namespace: serenditree
########################################################################################################################
# Branch
########################################################################################################################
branch:
  enabled: true
  wave: 15
  name: branch
  namespace: serenditree
  parameters:
    jsonWebKey: ~
    oidc:
      - country: ~
        idRef: ~
        id: ~
        secretRef: ~
        secret: ~
        urlRef: ~
        url: ~
########################################################################################################################
# Leaf
########################################################################################################################
leaf:
  enabled: true
  wave: 16
  name: leaf
  namespace: serenditree
