apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: fence-root-seed
  namespace: serenditree
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: mongodb
  ingress:
    - fromEndpoints:
        - {}
    - fromEntities:
        - cluster
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/component: mongodb
    - toServices:
        - k8sServiceSelector:
            selector:
              matchLabels:
                app.kubernetes.io/component: mongodb
