global:
  context: ~
  host: ~
  issuer: ~
  wait: ~
  wave: ~
terraGateway:
  name: serenditree
  proxyName: serenditree-proxy
  otelHost: ~
gateway-helm:
  deployment:
    pod:
      labels:
        serenditree.io/otel: gateway
  config:
    envoyGateway:
      rateLimit:
        backend:
          type: Redis
          redis:
            url: ~
