apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-exoscale-cluster-autoscaler
data:
  api-key: {{ .Values.terraScale.apikey | b64enc }}
  api-secret: {{ .Values.terraScale.secret | b64enc }}
  api-zone: {{ .Values.global.zone | b64enc }}
