---
apiVersion: v1
kind: Secret
metadata:
  name: root-user
  labels:
    app.kubernetes.io/name: root-user
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: root
    app.kubernetes.io/part-of: serenditree
type: Opaque
data:
  database-name: {{ .Values.db.name | b64enc }}
  database-user: {{ .Values.db.user | b64enc }}
  database-password: {{ .Values.db.password | b64enc }}
  database-root-password: {{ .Values.rootUser.password | b64enc }}
  mariadb-galera-mariabackup-password: {{ .Values.rootUser.password | b64enc }}
  mariadb-password: {{ .Values.db.password | b64enc }}
  mariadb-root-password: {{ .Values.rootUser.password | b64enc }}
