---
apiVersion: v1
kind: Secret
metadata:
  name: root-seed
  labels:
    {{- include "st-default-labels-component" . }}
type: Opaque
data:
  S3_ACCESS_KEY: {{ .Values.rootSeed.snapshot.accessKey | b64enc }}
  S3_SECRET_KEY: {{ .Values.rootSeed.snapshot.accessSecret | b64enc }}
