---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: root-map
  labels:
    app.kubernetes.io/name: root-map
    app.kubernetes.io/version: v0.0.1
    app.kubernetes.io/component: root
    app.kubernetes.io/part-of: serenditree
spec:
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: root-map
  template:
    metadata:
      labels:
        name: root-map
    spec:
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
      initContainers:
        - name: root-map-init
          image: "docker.io/amazon/aws-cli:latest"
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              aws configure set aws_access_key_id $(EXOSCALE_API_KEY)
              aws configure set aws_secret_access_key $(EXOSCALE_API_SECRET)
              aws configure set default.region at-vie-1
              aws configure set default.endpoint_url https://sos-at-vie-1.exo.io
              test -f $(MBTILES) || aws s3 cp s3://$(MBTILES_SOS) $(MBTILES)
              chown -R 1001:0 $(MBTILES_DIR)
          env:
            - name: MBTILES_SOS
              value: serenditree-data/osm.mbtiles
            - name: MBTILES_DIR
              value: {{ .Values.rootMap.dataMountPath }}
            - name: MBTILES
              value: {{ .Values.rootMap.dataMountPath }}/osm.mbtiles
            - name: EXOSCALE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: exoscale-credentials
                  key: apikey
            - name: EXOSCALE_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: exoscale-credentials
                  key: secret
          volumeMounts:
            - mountPath: {{ .Values.rootMap.dataMountPath }}
              name: root-map
      containers:
        - name: root-map
          image: "quay.io/serenditree/root-map:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SERENDITREE_DATA_URL
              value: {{ .Values.rootMap.data }}
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              port: 8080
              path: "/index.json"
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            httpGet:
              port: 8080
              path: "/index.json"
            failureThreshold: 20
            periodSeconds: 30
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            runAsGroup: 1001
            runAsUser: 1001
          volumeMounts:
            - mountPath: {{ .Values.rootMap.dataMountPath }}
              name: root-map
      volumes:
        - name: root-map
          persistentVolumeClaim:
            claimName: root-map

