---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: root-map
  labels:
    app.kubernetes.io/name: root-map
    app.kubernetes.io/version: v0.0.1
    app.kubernetes.io/component: root
    app.kubernetes.io/part-of: serenditree
spec:
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: root-map
  template:
    metadata:
      labels:
        name: root-map
    spec:
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
      initContainers:
        - name: exo
          image: "docker.io/exoscale/cli:latest"
          command:
            - 'sh'
            - '-c'
            - >
              test -f $MBTILES || /exo -A serenditree storage download $SOS_MBTILES $MBTILES
              chown 1001:0 $MBTILES
          env:
            - name: EXOSCALE_CONFIG
              value: /exoscale-config/exoscale.toml
            - name: SOS_MBTILES
              value: sos://serenditree-data/osm.mbtiles
            - name: MBTILES
              value: {{ .Values.rootMap.dataMountPath }}/osm.mbtiles
          volumeMounts:
            - mountPath: {{ .Values.rootMap.dataMountPath }}
              name: root-map
            - mountPath: "/exoscale-config"
              name: exoscale-config
      containers:
        - name: root-map
          image: "quay.io/serenditree/root-map:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SERENDITREE_DATA_URL
              value: {{ .Values.rootMap.data }}
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              port: 8080
              path: "/index.json"
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            httpGet:
              port: 8080
              path: "/index.json"
            failureThreshold: 20
            periodSeconds: 30
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            runAsGroup: 1001
            runAsUser: 1001
          volumeMounts:
            - mountPath: {{ .Values.rootMap.dataMountPath }}
              name: root-map
      volumes:
        - name: root-map
          persistentVolumeClaim:
            claimName: root-map
        - name: exoscale-config
          secret:
            secretName: exoscale-config

