{{- if eq "serenditree-kubernetes" .Values.global.context }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: map
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/global-rate-limit: "42"
    nginx.ingress.kubernetes.io/global-rate-limit-window: "1s"
    nginx.ingress.kubernetes.io/global-rate-limit-key: "${remote_addr}"
    cert-manager.io/cluster-issuer: "lets-encrypt-{{ .Values.ingress.letsencrypt.issuer }}"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.{{ .Values.rootMap.host }}
        - {{ .Values.rootMap.host }}
      secretName: serenditree-tls-{{ .Values.ingress.letsencrypt.issuer }}
  rules:
    - host: {{ .Values.rootMap.host }}
      http:
        paths:
          - path: /styles
            pathType: Prefix
            backend:
              service:
                name: root-map
                port:
                  number: 8080
          - path: /fonts
            pathType: Prefix
            backend:
              service:
                name: root-map
                port:
                  number: 8080
          - path: /data
            pathType: Prefix
            backend:
              service:
                name: root-map
                port:
                  number: 8080
{{- end }}
