{{- if hasPrefix "serenditree-kubernetes" .Values.global.context }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: map
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    cert-manager.io/issuer: "lets-encrypt-{{ .Values.ingress.letsencrypt.issuer }}"
spec:
  {{- if not (hasSuffix "local" .Values.global.context) }}
  tls:
    - hosts:
        - www.serenditree.io
        - serenditree.io
      secretName: serenditree-tls-{{ .Values.ingress.letsencrypt.issuer }}
  {{- end }}
  rules:
    - host: serenditree.io
      http:
        paths:
          - path: /styles
            pathType: Prefix
            backend:
              service:
                name: root-map
                port:
                  number: 8080
          - path: /fonts
            pathType: Prefix
            backend:
              service:
                name: root-map
                port:
                  number: 8080
          - path: /data
            pathType: Prefix
            backend:
              service:
                name: root-map
                port:
                  number: 8080
{{- end }}
