---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: leaf
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: leaf
  minReplicas: {{ .Values.leaf.minReplicas }}
  maxReplicas: {{ .Values.leaf.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
