{{- if eq "serenditree-kubernetes" .Values.global.context }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: leaf
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/global-rate-limit: "10"
    nginx.ingress.kubernetes.io/global-rate-limit-window: "1s"
    nginx.ingress.kubernetes.io/global-rate-limit-key: "${remote_addr}-${$request_uri}"
    cert-manager.io/issuer: "lets-encrypt-{{ .Values.ingress.letsencrypt.issuer }}"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.serenditree.io
        - serenditree.io
      secretName: serenditree-tls-{{ .Values.ingress.letsencrypt.issuer }}
  rules:
    - host: serenditree.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: leaf
                port:
                  number: 8080
{{- end }}
