---
apiVersion: v1
kind: Service
metadata:
  name: leaf
  labels:
    app.kubernetes.io/name: leaf
    app.kubernetes.io/version: v0.0.1
    app.kubernetes.io/component: leaf
    app.kubernetes.io/part-of: serenditree
spec:
  type: ClusterIP
  selector:
    name: leaf
  ports:
    - name: leaf
      port: 8080
      targetPort: 8080
      protocol: TCP
