apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-map
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:serenditree/stem.git'
    path: plots/root/map
    targetRevision: dev
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: rootMap.app
          value: "true"
        - name: global.context
          value: {{ .Values.global.context }}
        - name: root-map-app.rootMap.host
          value: {{ .Values.rootMap.host | quote }}
        - name: root-map-app.ingress.letsencrypt.issuer
          value: {{ .Values.ingress.letsencrypt.issuer }}
        - name: root-map-app.rootMap.minReplicas
          value: {{ .Values.rootMap.minReplicas | quote }}
        - name: root-map-app.rootMap.maxReplicas
          value: {{ .Values.rootMap.maxReplicas | quote }}
        - name: root-map-app.rootMap.dataMountPath
          value: {{ .Values.rootMap.dataMountPath }}
        - name: root-map-app.rootMap.stage
          value: {{ .Values.rootMap.stage }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: serenditree
