---
apiVersion: v1
kind: ConfigMap
metadata:
  name: root-seed-init
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/version: v0.0.1
    app.kubernetes.io/component: root
    app.kubernetes.io/part-of: serenditree
data:
  init.js: |-
{{ .Files.Get "resources/0.0.1-init.js" | indent 4 }}
