---
apiVersion: v1
kind: Secret
metadata:
  name: root-seed
  labels:
    app.kubernetes.io/name: root-seed
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: root
    app.kubernetes.io/part-of: serenditree
type: Opaque
data:
  database-name: {{ .Values.auth.databases | b64enc }}
  database-user: {{ .Values.auth.usernames | b64enc }}
  database-password: {{ .Values.auth.passwords | b64enc }}
  database-root-password: {{ .Values.auth.rootPassword | b64enc }}
  mongodb-passwords: {{ .Values.auth.passwords | b64enc }}
  mongodb-replica-set-key: {{ .Values.auth.rootPassword | b64enc }}
  mongodb-root-password: {{ .Values.auth.rootPassword | b64enc }}
