apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: branch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:serenditree/stem.git'
    path: plots/branch
    targetRevision: dev
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: branch.app
          value: "true"
        - name: global.context
          value: {{ .Values.global.context }}
        - name: branch-app.branch.minReplicas
          value: {{ .Values.branch.minReplicas | quote }}
        - name: branch-app.branch.maxReplicas
          value: {{ .Values.branch.maxReplicas | quote }}
        - name: branch-app.branch.stage
          value: {{ .Values.branch.stage }}
        - name: branch-app.ingress.letsencrypt.issuer
          value: {{ .Values.ingress.letsencrypt.issuer }}
        - name: branch-app.branch.jsonWebKey.encryption
          value: {{ .Values.branch.jsonWebKey.encryption }}
        - name: branch-app.branch.jsonWebKey.signature
          value: {{ .Values.branch.jsonWebKey.signature }}
        {{- $index := 0 }}
        {{- range $oidc := .Values.branch.oidc }}
        {{- range $key, $value := $oidc }}
        - name: branch-app.branch.oidc[{{ $index }}].{{ $key }}
          value: {{ $value }}
        {{- end}}
        {{- $index = add1 $index }}
        {{- end}}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: serenditree
