global:
  context: ~
kafka:
  name: root-wind
  replicas: 3
  topics: 2
  partitions: 4
  replicationFactor: 2
  storage: 20 # storage size in GB
  logRetentionHours: 12
  messageMaxBytes: 1000000 # 1MB
  messageBatchFactor: 1
  requestTimeoutMs: 1000
  compressionType: uncompressed
