apiVersion: v2
type: application
name: terra-apisix
description: "API Gateway resources"
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: apisix
    version: 2.0.0
    repository: https://charts.apiseven.com
