---
apiVersion: v1
kind: ConfigMap
metadata:
  name: branch
  labels:
    app.kubernetes.io/name: branch
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: branch
    app.kubernetes.io/part-of: serenditree
data:
  serenditree.seed.water.retention: "21"
  serenditree.host: "https://{{ .Values.branch.host }}"
