# only local for now
{{- if eq "serenditree-kubernetes-local" .Values.global.context }}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: branch
spec:
  http:
    {{- range .Values.global.branches }}
    - name: {{ . }}
      match:
        hosts:
          - serenditree.io
        paths:
          - /api/v1/{{ . }}
      backends:
          {{- if eq "garden" . }}
        - serviceName: branch-seed
          {{- else }}
        - serviceName: branch-{{ . }}
          {{- end}}
          servicePort: 8080
    {{- end }}
  {{- end }}
