{{- if eq "serenditree-kubernetes" .Values.global.context }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: branch
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    cert-manager.io/issuer: "lets-encrypt-{{ .Values.ingress.letsencrypt.issuer }}"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.serenditree.io
        - serenditree.io
      secretName: serenditree-tls-{{ .Values.ingress.letsencrypt.issuer }}
  rules:
    - host: serenditree.io
      http:
        paths:
          {{- range .Values.global.branches }}
          - path: /api/v1/{{ . }}
            pathType: Prefix
            backend:
              service:
                {{- if eq "garden" . }}
                name: branch-seed
                {{- else }}
                name: branch-{{ . }}
                {{- end}}
                port:
                  number: 8080
          {{- end }}
{{- end }}
