apiVersion: v1
kind: Secret
metadata:
  name: branch
  labels:
    app.kubernetes.io/name: branch
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: branch
    app.kubernetes.io/part-of: serenditree
type: Opaque
data:
  json-web-key: {{ .Values.branch.jsonWebKey.encryption | b64enc }}
{{/*  {{- range .Values.branch.oidc }}*/}}
{{/*  {{ .idRef }}: {{ .id | b64enc }}*/}}
{{/*  {{ .secretRef }}: {{ .secret | b64enc }}*/}}
{{/*  {{ .urlRef }}: {{ .url | b64enc }}*/}}
{{/*  {{- end}}*/}}
