{{ range without .Values.global.branches "garden" }}
{{- $serviceName := printf "%s-%s" "branch" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    app.kubernetes.io/name: {{ $serviceName }}
    app.kubernetes.io/version: v0.0.1
    app.kubernetes.io/component: branch
    app.kubernetes.io/part-of: serenditree
spec:
  type: ClusterIP
  selector:
    name: {{ $serviceName }}
  ports:
    - name: {{ $serviceName }}
      port: 8080
      targetPort: 8080
      protocol: TCP
{{- end }}
