{{- if .Values.global.setupPolicies }}
{{ range tuple "root-seed/mongodb" "root-user/mariadb-galera" }}
{{- $component := substr 10 100 . }}
{{- $name := substr 0 9 . }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: fence-{{ $name }}
  namespace: serenditree
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: {{ $component }}
  ingress:
    - fromEndpoints:
        - {}
    - fromEntities:
        - cluster
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/component: {{ $component }}
    - toServices:
        - k8sServiceSelector:
            selector:
              matchLabels:
                app.kubernetes.io/component: {{ $component }}
{{- end }}
{{- end }}
