{{- if .Values.letsencrypt.dns.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.letsencrypt.dns.secretName }}
type: Opaque
stringData:
  EXOSCALE_API_KEY: {{ .Values.letsencrypt.dns.key }}
  EXOSCALE_API_SECRET: {{ .Values.letsencrypt.dns.secret }}
{{- end }}
