{{- if .Values.apisix.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: apisix
spec:
  groups:
    - name: ApisixRules
      rules:
        - alert: apisix_http_status_errors
          expr: count(rate(apisix_http_status{code=~"(4|5).*"}[10m])) > 100
{{- end }}
