---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-leaf-workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
