---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ index .Values "postgresql-ha" "postgresql" "initdbScriptsCM" }}
  labels:
    {{- include "st-default-labels-component" . }}
data:
  init.sql: |-
{{ .Files.Get "resources/0.0.1-init.sql" | indent 4 }}
