---
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "postgresql-ha" "postgresql" "existingSecret" }}
  labels:
    {{- include "st-default-labels-component" . }}
type: Opaque
data:
  # quarkus-compatibility
  database-name: {{ .Values.rootUser.db.name | b64enc }}
  database-user: {{ .Values.rootUser.db.user | b64enc }}
  database-password: {{ .Values.rootUser.db.password | b64enc }}
  database-root-password: {{ .Values.rootUser.rootUser.password | b64enc }}
  # postgres-ha
  password: {{ .Values.rootUser.db.password | b64enc }}
  postgres-password: {{ .Values.rootUser.rootUser.password | b64enc }}
  repmgr-password: {{ .Values.rootUser.rootUser.password | b64enc }}
  sr-check-password: {{ .Values.rootUser.rootUser.password | b64enc }}
  # pg-pool
  admin-password: {{ .Values.rootUser.rootUser.password | b64enc }}
  usernames: {{ printf "%s,%s" "postgres" .Values.rootUser.db.user | b64enc }}
  passwords: {{ printf "%s,%s" .Values.rootUser.rootUser.password .Values.rootUser.db.password | b64enc }}
  # backup
  apikey: {{ .Values.rootUser.backup.apikey | b64enc }}
  secret: {{ .Values.rootUser.backup.secret | b64enc }}
