---
apiVersion: v1
kind: Secret
metadata:
  name: root-user
  labels:
    app.kubernetes.io/name: root-user
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: root
    app.kubernetes.io/part-of: serenditree
type: Opaque
data:
  database-name: {{ .Values.rootUser.db.name | b64enc }}
  database-user: {{ .Values.rootUser.db.user | b64enc }}
  database-password: {{ .Values.rootUser.db.password | b64enc }}
  database-root-password: {{ .Values.rootUser.rootUser.password | b64enc }}
  postgres-password: {{ .Values.rootUser.rootUser.password | b64enc }}
  password: {{ .Values.rootUser.db.password | b64enc }}
  repmgr-password: {{ .Values.rootUser.rootUser.password | b64enc }}
  admin-password: {{ .Values.rootUser.rootUser.password | b64enc }}
  usernames: {{ "postgres" | b64enc }}
  passwords: {{ .Values.rootUser.rootUser.password | b64enc }}
