#!/bin/sh
# shellcheck disable=SC2016
ENV_SUBST_SERENDITREE='$SERENDITREE_CONTENT $SERENDITREE_STAGE'
ENV_SUBST_OTEL='$OTEL_ENABLED $OTEL_HOST $OTEL_PORT $OTEL_SERVICE $OTEL_SPAN'

envsubst "$ENV_SUBST_SERENDITREE $ENV_SUBST_OTEL" <serenditree.conf >"$SERENDITREE_CONFIG"
exec "$SERENDITREE_BIN" -g 'daemon off;'
