---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: branch
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: terra-vault
    kind: ClusterSecretStore
  target:
    name: branch
  data:
    - secretKey: json-web-key
      remoteRef:
        key: serenditree/app/branch/jsonWebKey
        property: value
    {{- range .Values.branch.oidc }}
    - secretKey: oidc-id-{{ . }}
      remoteRef:
        key: serenditree/oidc/{{ . }}/id
        property: value
    - secretKey: oidc-secret-{{ . }}
      remoteRef:
        key: serenditree/oidc/{{ . }}/secret
        property: value
    - secretKey: oidc-url-{{ . }}
      remoteRef:
        key: serenditree/oidc/{{ . }}/url
        property: value
    {{- end }}
