apiVersion: v1
kind: Secret
metadata:
  name: branch
  labels:
    {{- include "st-default-labels" . }}
type: Opaque
data:
  json-web-key: {{ .Values.branch.jsonWebKey | b64enc }}
  {{- range .Values.branch.oidc }}
  {{ .idRef }}: {{ .id | b64enc }}
  {{ .secretRef }}: {{ .secret | b64enc }}
  {{ .urlRef }}: {{ .url | b64enc }}
  {{- end }}
