{{- if .Values.kafdrop.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafdrop
    io.serenditree.service: kafdrop
  name: kafdrop
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.serenditree.service: kafdrop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafdrop
    io.serenditree.service: kafdrop
  name: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.serenditree.service: kafdrop
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.serenditree.service: kafdrop
    spec:
      containers:
        - env:
            - name: KAFKA_BROKERCONNECT
              value: root-wind.serenditree.svc.{{ .Values.global.clusterDomain }}:9092
          image: obsidiandynamics/kafdrop:latest
          imagePullPolicy: Always
          name: kafdrop
          ports:
            - containerPort: 9000
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 512Mi
      restartPolicy: Always
{{- end }}
