ingress-nginx:
  controller:
    kind: DaemonSet
    config:
      global-rate-limit-status-code: "429"
      global-rate-limit-memcached-host: "host-set-via-argo-param"
      global-rate-limit-memcached-port: "11211"
      global-rate-limit-memcached-connect-timeout: "50ms"
      global-rate-limit-memcached-max-idle-timeout: "50ms"
      global-rate-limit-memcached-pool-size: "10"
      enable-modsecurity: "true"
      enable-owasp-modsecurity-crs: "true"
#      enable-opentelemetry: "true"
#      opentelemetry-operation-name: "ingress"
#      opentelemetry-trust-incoming-span: "false"
#      otel-service-name: "ingress-nginx"
#      otlp-collector-host: "host-set-via-argo-param"
    service:
      externalTrafficPolicy: Local
      annotations:
        service.beta.kubernetes.io/exoscale-loadbalancer-service-healthcheck-interval: "10s"
        service.beta.kubernetes.io/exoscale-loadbalancer-service-healthcheck-mode: "http"
        service.beta.kubernetes.io/exoscale-loadbalancer-service-healthcheck-retries: '1'
        service.beta.kubernetes.io/exoscale-loadbalancer-service-healthcheck-timeout: "3s"
        service.beta.kubernetes.io/exoscale-loadbalancer-service-healthcheck-uri: "/"
        service.beta.kubernetes.io/exoscale-loadbalancer-name: "serenditree"
        service.beta.kubernetes.io/exoscale-loadbalancer-service-strategy: "round-robin"
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
      type: RollingUpdate
