apiVersion: v2
type: application
name: terra-scope
description: Prometheus resources.
version: 0.0.1
appVersion: 0.0.1
dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 86.1.1
  - name: commons
    repository: oci://quay.io/serenditree/charts
    version: 0.0.1
    condition: global.wait
