{{- if .Values.global.setupApps }}
{{- if not (hasSuffix "-local" .Values.global.context) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terra-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:serenditree/stem.git'
    targetRevision: dev
    path: plots/terra/charts/ingress
    kustomize:
      namespace: ingress-nginx
      patches:
        - patch: |-
            - op: add
              path: /data/global-rate-limit-memcached-host
              value: terra-cache-memcached.ingress-nginx.svc.{{ .Values.global.clusterDomain }}
          target:
            kind: ConfigMap
            name: ingress-nginx-controller
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
{{- end }}
{{- end }}
