{{- if not (hasSuffix "-local" .Values.global.context) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terra-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:serenditree/stem.git'
    targetRevision: dev
    path: plots/terra/charts/ingress
    kustomize:
      namespace: ingress-nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
{{- end }}
