{{- if .Values.global.setupApps }}
{{- if not (hasSuffix "-local" .Values.global.context) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terra-issuer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:serenditree/stem.git'
    path: plots/terra/charts/issuer
    targetRevision: dev
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: letsencrypt.issuer
          value: {{ .Values.ingress.letsencrypt.issuer }}
        - name: letsencrypt.email
          value: {{ .Values.ingress.letsencrypt.email }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: serenditree
{{- end }}
{{- end }}
