argo-cd:
  configs:
    secret:
      argocdServerAdminPassword: ~
global:
  setupApps: ~
  setupScale: false
  setupScope: false
  setupTekton: false
  context: ~
  clusterDomain: ~
certs:
  letsencrypt:
    issuer: ~
    email: ~
strimzi:
  kafdrop:
    enabled: false
tekton:
  webhook: ~
  basic:
    github: ~
    quay: ~
    redhat: ~
