apiVersion: batch/v1
kind: Job
metadata:
  name: seed-restore
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: delete-seed
          image: docker.io/curlimages/curl:latest
          args:
            - --request
            - DELETE
            - 'http://root-seed:9200/seed'
        - name: delete-garden
          image: docker.io/curlimages/curl:latest
          args:
            - --request
            - DELETE
            - 'http://root-seed:9200/garden'
      containers:
        - name: seed-restore
          image: docker.io/curlimages/curl:latest
          args:
            - --request
            - POST
            - 'http://root-seed:9200/_snapshot/seed-backup/$_latest_snapshot/_restore'
            - --header
            - 'Content-Type: application/json'
            - --data
            - '{"indices": "seed,garden"}'
