apiVersion: batch/v1
kind: CronJob
metadata:
  name: user-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: user-backup
              emptyDir: { }
            - name: exoscale-config
              secret:
                secretName: exoscale-config
          restartPolicy: OnFailure
          initContainers:
            - name: mariadb
              image: quay.io/serenditree/root-user:latest
              command:
                - /bin/sh
                - -c
              args:
               - >-
                 mariadb-dump 
                 -h root-user 
                 -u root 
                 -p$(ROOT_PASSWORD) 
                 serenditree | gzip > /user-backup/user-backup.gz
              env:
                - name: ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: root-user
                      key: database-root-password
              volumeMounts:
                - mountPath: "/user-backup"
                  name: user-backup
          containers:
            - name: exo
              image: docker.io/exoscale/cli:latest
              args:
                - --use-account=serenditree
                - storage
                - upload
                - /user-backup/user-backup.gz
                - sos://serenditree-backup
              env:
                - name: EXOSCALE_CONFIG
                  value: /exoscale-config/exoscale.toml
              volumeMounts:
                - mountPath: "/user-backup"
                  name: user-backup
                - mountPath: "/exoscale-config"
                  name: exoscale-config
