apiVersion: v2
type: application
name: root-seed
description: MongoDB resources
version: 0.0.1
appVersion: "v0.0.1"

dependencies:
  - name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: 16.3.0
    condition: rootSeed.mongodb
