apiVersion: v2
type: application
name: root-seed
description: OpenSearch resources
version: 0.0.1
appVersion: 0.0.1
dependencies:
  - name: opensearch
    repository: https://charts.bitnami.com/bitnami
    version: 1.9.1
  - name: commons
    repository: oci://quay.io/serenditree/charts
    version: 0.0.1
