apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.metastore.retention }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      volumes:
        - name: {{ .Values.metastore.retention }}
          configMap:
            name: {{ .Values.metastore.retention }}
      restartPolicy: Never
      containers:
        - name: postgres
          image: quay.io/serenditree/root-user:latest
          command:
            - psql
          args:
            - $(QW_METASTORE_URI)
            - --file=/metastore/retention.sql
            - --no-password
          env:
            - name: QW_METASTORE_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.metastore.secretUriRef }}
                  key: QW_METASTORE_URI
          volumeMounts:
            - mountPath: "/metastore"
              name: {{ .Values.metastore.retention }}
