---
apiVersion: v1
kind: Secret
metadata:
  name: quickwit-metastore
type: Opaque
data:
  {{- with .Values.postgresql.auth }}
  QW_METASTORE_URI: {{ printf "postgres://%s:%s@metastore:5432/metastore" .username .password | b64enc }}
  {{- end }}

