apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-credentials
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: s3-credentials
  data:
    - secretKey: QW_STORAGE_S3_ACCESS_KEY_ID
      remoteRef:
        key: serenditree/iam/traces/access
        property: value
    - secretKey: QW_STORAGE_S3_SECRET_ACCESS_KEY
      remoteRef:
        key: serenditree/iam/traces/secret
        property: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.metastore.secretUriRef }}
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: {{ .Values.metastore.secretUriRef }}
  data:
    - secretKey: QW_METASTORE_URI
      remoteRef:
        key: serenditree/o11y/terraTraces/metastore/uri
        property: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.metastore.secretRef }}
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: {{ .Values.metastore.secretRef }}
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: serenditree/o11y/terraTraces/metastore/username
        property: value
    - secretKey: password
      remoteRef:
        key: serenditree/o11y/terraTraces/metastore/password
        property: value
