apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rootMap.secret }}
  labels:
    {{- include "st-default-labels-component" . }}
data:
  apikey: {{ .Values.rootMap.data.apikey | b64enc }}
  secret: {{ .Values.rootMap.data.secret | b64enc }}
