{{- $unique := dict }}
{{- $nsExists := list .Values.terraCilium.namespace .Values.terraArgocd.namespace }}
{{- range $key, $value := .Values }}
  {{- if and $value.namespace (not (has $value.namespace $nsExists)) (not (hasKey $unique $value.namespace)) }}
    {{- $unique = set $unique $value.namespace true }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $value.namespace }}
  {{- end }}
{{- end }}
