---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.terraStreams.name }}
  namespace: {{ .Values.global.cdNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.terraStreams.wave | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repository | quote }}
    path: "{{ .Values.global.terraPath }}/{{ trimPrefix .Values.global.terraPrefix .Values.terraStreams.name }}"
    targetRevision: {{ .Values.terraStreams.revision | default .Values.global.revision | quote }}
    helm:
      parameters:
        - name: global.context
          value: {{ .Values.global.context }}
        - name: global.clusterDomain
          value: {{ .Values.global.clusterDomain }}
        - name: strimzi-kafka-operator.kubernetesServiceDnsDomain
          value: {{ .Values.global.clusterDomain }}
  destination:
    server: {{ .Values.global.destinationServer }}
    namespace: {{ .Values.terraStreams.namespace }}
  syncPolicy:
    automated: {{ .Values.global.automated | toYaml | nindent 6 }}
    retry: {{ .Values.global.retry | toYaml | nindent 6  }}
    syncOptions:
      - CreateNamespace=true
