{{- if .Values.terraTekton.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.terraTekton.name }}
  namespace: {{ .Values.global.argocdNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.terraTekton.wave | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repository | quote }}
    path: "{{ .Values.global.terraPath }}/{{ trimPrefix .Values.global.terraPrefix .Values.terraTekton.name }}"
    targetRevision: {{ .Values.terraTekton.revision | default .Values.global.revision | quote }}
    helm:
      parameters:
        - name: global.wait
          value: {{ .Values.global.wait | quote }}
        - name: global.wave
          value: {{ .Values.terraTekton.wave | quote }}
        - name: global.context
          value: {{ .Values.global.context }}
  destination:
    server: {{ .Values.global.destinationServer }}
    namespace: {{ .Values.terraTekton.namespace }}
  syncPolicy:
    automated: {{ .Values.global.automated | toYaml | nindent 6 }}
    retry: {{ .Values.global.retry | toYaml | nindent 6  }}
{{- end }}
