apiVersion: v2
type: application
name: terra-scale
description: "Cluster-autoscaler resources"
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: cluster-autoscaler
    repository: https://kubernetes.github.io/autoscaler
    version: 9.40.0
