apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: serenditree-argocd
spec:
  params:
    - name: TIMEOUT
      description: 'Timeout for healthcheck in seconds.'
      type: string
      default: '420'
  stepTemplate:
    envFrom:
      - configMapRef:
          name: argocd-config
      - secretRef:
          name: argocd-token
  steps:
    - name: sync
      image: argoproj/argocd:latest
      script: |
        argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure --plaintext
        argocd app sync $ARGOCD_APPLICATION --server $ARGOCD_SERVER
        argocd app wait $ARGOCD_APPLICATION --server $ARGOCD_SERVER --health --timeout $(params.TIMEOUT)
