---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-containers
  labels:
    app.kubernetes.io/component: tekton
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
