---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: serenditree-finally
  labels:
    app.kubernetes.io/component: tekton
spec:
  description: 'Task to react to and notify about pipeline completion.'
  params:
    - name: pipeline
      type: string
      description: 'Name of the pipeline.'
    - name: revision
      type: string
      description: 'Name of the revision to build.'
    - name: run
      type: string
      default: undefined
      description: 'ID of the pipeline run.'
    - name: status
      type: string
      description: 'Aggregated status of the pipeline.'
    - name: details
      type: array
      description: 'Array of task:status pairs.'
  stepTemplate:
    env:
      - name: WEBHOOK
        valueFrom:
          secretKeyRef:
            name: webhook
            key: webhook
  steps:
    - name: notify
      image: alpine/curl
      args:
        - $(params.details)
      script: |
{{ .Files.Get "resources/finally.sh" | indent 8 }}
