---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: serenditree-finally
  labels:
    app.kubernetes.io/component: tekton
spec:
  description: 'Task to react to and notify about pipeline completion.'
  params:
    - name: PIPELINE_NAME
      type: string
      description: 'Name of the pipeline.'
    - name: PIPELINE_STATUS
      type: array
      description: 'Array of task:status pairs.'
    - name: PIPELINE_AGGREGATE_STATUS
      type: string
      description: 'Aggregated status of the pipeline.'
    - name: PIPELINE_REVISION
      type: string
      description: 'Name of the revision to build.'
    - name: PIPELINE_RUN
      type: string
      default: undefined
      description: 'UID of the pipeline run.'
  stepTemplate:
    env:
      - name: WEBHOOK
        valueFrom:
          secretKeyRef:
            name: webhook
            key: webhook
  steps:
    - name: notify
      image: alpine/curl
      args:
        - $(params.PIPELINE_STATUS)
      script: |-
{{ .Files.Get "resources/finally.sh" | indent 8 }}
