---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: 'serenditree'
  password: {{ .Values.basic.github | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-token
  annotations:
    tekton.dev/docker-0: https://quay.io
type: kubernetes.io/basic-auth
stringData:
  username: 'serenditree'
  password: {{ .Values.basic.quay | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redhat-token
  annotations:
    tekton.dev/docker-0: https://registry.redhat.io
type: kubernetes.io/basic-auth
stringData:
  username: '11330181|serenditree'
  password: {{ .Values.basic.redhat | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook
type: Opaque
data:
  webhook: {{ .Values.webhook | b64enc }}
