{{- if hasPrefix "serenditree-kubernetes" .Values.global.context }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipelines
secrets:
  - name: github-token
  - name: quay-token
  - name: redhat-token
{{- end }}
